const BlogData = [
  {
    id: 1,
    date: "January 11, 2024",
    catgeory: "Deluxe Room",
    title: "Deluxe Room",
    cover: "/images/singlepage/blog-1.jpg",
    desc: "A Deluxe Room is a type of hotel accommodation that typically offers more space and amenities compared to a standard room. It's often designed to provide extra comfort and luxury for guests. Features commonly found in a Deluxe Room may include a larger bed, a sitting area with a sofa or chairs, a work desk, upgraded bathroom amenities, and sometimes additional perks like complimentary breakfast or access to exclusive lounges. The exact amenities and layout can vary depending on the hotel's standards and the specific room design.",
    para: "This Room is very Beautiful",
  },
  {
    id: 2,
    date: "March 15, 2024",
    catgeory: "Outdoor Pools",
    title: "Swimming Pool",
    cover: "/images/singlepage/blog-2.jpg",
    para1: "Beautiful Place to Relax",
    desc2: "An outdoor pool is a swimming pool located outside, usually in a garden, courtyard, or open area. Outdoor pools come in various shapes and sizes, ranging from small, private pools to large, resort-style pools. They are typically surrounded by lounge chairs, umbrellas, and sometimes cabanas or pavilions for shade and relaxation. Outdoor pools are often heated to a comfortable temperature and may feature additional amenities such as poolside bars, water features like fountains or waterfalls, and sometimes even water slides or recreational areas for children. They are popular in hotels, resorts, and recreational facilities, offering a refreshing escape and a place to unwind outdoors.",
  },
  {
    id: 3,
    date: "June 21, 2024",
    catgeory: "Single Room",
    title: "Single Room",
    cover: "/images/singlepage/blog-3.jpg",
    para3: "This Room is very Beautiful",
    desc4: "A single room is a type of hotel accommodation designed for one guest. It typically features a single bed, although some single rooms may have a slightly larger bed, such as a twin or a twin XL. Single rooms are smaller in size compared to double or queen rooms and are usually more affordable. They are equipped with basic amenities such as a bedside table, a chair, a small desk or work area, and a closet or wardrobe for storage. Single rooms often have a private bathroom, but this can vary depending on the hotel or accommodation type.",
  },
  {
    id: 4,
    date: "July 30, 2024",
    catgeory: "Outdoor Pools",
    title: "Relaxation Pools",
    cover: "/images/singlepage/blog-4.jpg",
    para5: "Provide a relaxing, warm water experience.",
    desc6: "An outdoor pool is a swimming pool located outside, usually in a garden, courtyard, or open area. Outdoor pools come in various shapes and sizes, ranging from small, private pools to large, resort-style pools. They are typically surrounded by lounge chairs, umbrellas, and sometimes cabanas or pavilions for shade and relaxation. Outdoor pools are often heated to a comfortable temperature and may feature additional amenities such as poolside bars, water features like fountains or waterfalls, and sometimes even water slides or recreational areas for children. They are popular in hotels, resorts, and recreational facilities, offering a refreshing escape and a place to unwind outdoors.",
  },
  {
    id: 5,
    date: "November 10, 2024",
    catgeory: "Beach",
    title: "Private Beach",
    cover: "/images/singlepage/beach.jpg",
    para7: "Relaxing and place to Date in your partner",
    desc8: "A beach is a landform alongside a body of water which consists of loose particles. The particles composing a beach are typically made from rock, such as sand, gravel, shingle, pebbles, etc., or biological sources, such as mollusk shells or coralline algae. Beaches typically occur in coastal areas where wave or current action deposits and reworks sediments. Beaches provide a unique environment for a variety of recreational activities such as swimming, surfing, sunbathing, and beachcombing. They are also important ecosystems providing habitat for various species of plants and animals.",
  },
  {
    id: 6,
    date: "May 18, 2024",
    catgeory: "Outdoor Pools",
    title: "Heated Pools",
    cover: "/images/singlepage/blog-6.jpg",
    para9: "Best Relaxing Pools",
    desc10: "Outdoor pools are large, water-filled recreational areas located outside, often within a landscaped area. They are designed for swimming, relaxation, and recreation. Outdoor pools can vary greatly in size and shape, from small, private pools to large, resort-style pools. They are typically surrounded by amenities such as lounge chairs, umbrellas, and sometimes cabanas or pavilions for shade. Many outdoor pools are heated to a comfortable temperature, allowing for use in various weather conditions. They may also feature additional amenities like poolside bars, water features such as fountains or waterfalls, and sometimes even water slides or children's play areas. Outdoor pools are popular in hotels, resorts, and recreational centers, providing a relaxing and refreshing escape for guests and visitors. ",
  },
  {
    id: 7,
    date: "April 12, 2024",
    catgeory: "Twin BedRoom",
    title: "Features a double bed",
    cover: "/images/singlepage/room2.jpg",
    para11: "Similar to a double room but with two separate single beds.",
    desc12: "A twin bedroom is a type of hotel or residential accommodation that features two separate beds. These beds are typically sized for individual sleepers and are often referred to as twin beds. Twin bedrooms are designed to accommodate two people in the same room while providing them with their own separate sleeping space. In addition to the beds, a twin bedroom may include amenities such as bedside tables, lamps, a dresser or wardrobe for storage, and possibly a desk or seating area. Depending on the location and level of luxury, twin bedrooms may also offer en-suite bathrooms or shared bathroom facilities. Twin bedrooms are commonly found in hotels, motels, hostels, and guesthouses, offering a convenient and cost-effective option for travelers who prefer separate beds.",
  },
  {
    id: 7,
    date: "August 30, 2024",
    catgeory: "Luxury Room",
    title: "Presidential Suite or Royal Suite",
    cover: "/images/singlepage/room3.jpg",
    para13: "Presidential Suite",
    desc14: "Great comfort, especially as provided by expensive and beautiful things elegance, and comfort. A luxury bedroom is a high-end, lavish sleeping space designed to provide ultimate comfort and indulgence. These bedrooms are often found in upscale hotels, resorts, and luxury homes. Overall, a luxury bedroom is designed to provide a sumptuous and relaxing environment that offers a sense of opulence and indulgence.",
  },
  {
    id: 8,
    date: "July 10, 2024",
    catgeory: "Twin BedRoom",
    title: "Features a double bed",
    cover: "/images/singlepage/room1.png",
    para15: "The Room with two single beds that can accommodate two people.",
    desc16: "A twin bedroom is a type of accommodation that features two separate beds, each typically sized for individual sleepers. Twin bedrooms are commonly found in hotels, motels, hostels, and guesthouses, offering a convenient option for travelers who prefer separate beds. n addition to the beds, a twin bedroom may include amenities such as bedside tables, lamps, a dresser or wardrobe for storage, and possibly a desk or seating area. Depending on the location and level of luxury, twin bedrooms may also offer en-suite bathrooms or shared bathroom facilities. Twin bedrooms are a practical choice for accommodating two people in the same room while providing them with their own separate sleeping space. They are often chosen by friends traveling together, siblings, or in situations where couples prefer separate beds.",
  },
];

export default BlogData;
