const Sdata = [
    {
      id: 1,
      title: "Oriando",
      image: "/images/dest-1.jpg",
      desc: "Orlando is a city located in the central part of Florida, United States. It is known for its theme parks, including Walt Disney World, Universal Orlando, and SeaWorld. Orlando is a popular tourist destination, attracting millions of visitors each year.",
      desc2: "The city has a population of approximately 286,000 people and is the seat of Orange County. Orlando is also a significant economic center, with a diverse range of industries, including tourism, healthcare, and technology. The city is served by the Orlando International Airport, which is one of the busiest airports in the United States.",
      desc3: "Orlando has since evolved into a major metropolitan area known for its diverse economy, vibrant culture, and as a hub for tourism, technology, and higher education.",
      desc4: "The city of Orlando was officially incorporated on July 31, 1875. Its name is thought to be derived from the name of Orlando Reeves, a soldier who, according to local legend, died in the area during the Second Seminole War. However, this account has several variations and is considered more folklore than documented history. Another theory suggests that the city was named after a character in William Shakespeare's play 'As You Like It.'",
      sidepara: "Orlando, Florida, has a rich and diverse history that dates back centuries. The area was originally inhabited by Native American tribes, including the Seminole tribe. European settlers arrived in the 19th century, and the region saw significant development in the following decades.",
      sidepara3: "We can serve you the best services in this Hotel",
      sidepara4: "Our service is the best in all the Hotels",
      sidepara5: "Please Contant Our Phone Number",
      paraImage_one: "/images/singlepage/single-1.jpg",
      paraImage_two: "/images/singlepage/single-2.jpg",
    },
    {
      id: 2,
      title: "Miami",
      image: "/images/dest-2.jpg",
      desc5: "Miami's modern history began in the 19th century. The United States acquired Florida from Spain in 1821, and the area began to attract settlers. Julia Tuttle, a local landowner often called the 'Mother of Miami', played a pivotal role in the city's development. She persuaded railroad magnate Henry Flagler to extend his Florida East Coast Railway to Miami by sending him a fresh orange blossom during a harsh winter that devastated crops in the rest of Florida, demonstrating the area's potential for agriculture and tourism.",
      sidepara2: "Miami, Florida, is a city with a fascinating history that reflects its diverse cultural and economic evolution. The area where Miami now stands was originally inhabited by the Tequesta Native American tribe for thousands of years before European settlers arrived. In the 16th century, Spanish explorers first visited the region, but it wasn't until much later that significant development began.",
      sidepara3: "We can serve you the best services in this Hotel",
      sidepara4: "Our service is the best in all the Hotels",
      sidepara5: "Please Contant Our Phone Number",
    },
    {
      id: 3,
      title: "Los Angeles",
      image: "/images/dest-3.jpg",
      desc6: "Los Angeles, California, has a rich and varied history that reflects its multicultural influences and dynamic growth. The region was originally inhabited by Native American tribes, particularly the Tongva (or Gabrielino) people, who lived in the area for thousands of years.",
      sidepara6: "Los Angeles was officially founded on September 4, 1781, by a group of 44 settlers known as 'Los Pobladores.' They established El Pueblo de Nuestra Señora la Reina de los Ángeles de Porciúncula, which translates to 'The Town of Our Lady the Queen of the Angels of Porciúncula.' This small agricultural community grew around the Los Angeles River.",
      sidepara3: "We can serve you the best services in this Hotel",
      sidepara4: "Our service is the best in all the Hotels",
      sidepara5: "Please Contant Our Phone Number",
    },
    {
      id: 4,
      title: "San Diego",
      image: "/images/dest-4.jpg",
      desc7: "San Diego, California, has a rich and diverse history that dates back thousands of years. The area was originally inhabited by the Kumeyaay people, who lived there for thousands of years before the arrival of Europeans.",
      sidepara7: "San Diego was officially incorporated as a city on March 27, 1850, just months before California became a state. The arrival of the railroad in the late 19th century was a major catalyst for growth, connecting San Diego to the rest of the country and promoting trade and development.",
      sidepara3: "We can serve you the best services in this Hotel",
      sidepara4: "Our service is the best in all the Hotels",
      sidepara5: "Please Contant Our Phone Number",
    },
    {
      id: 5,
      title: "Houston",
      image: "/images/dest-5.jpg",
      desc8: "Houston, Texas, has a rich history that reflects its development from a modest settlement into one of the largest and most dynamic cities in the United States. The area that is now Houston was originally inhabited by various Native American tribes, including the Karankawa and Atakapa.",
      sidepara8: "Houston was founded on August 30, 1836, by brothers Augustus Chapman Allen and John Kirby Allen. They purchased 6,642 acres of land along Buffalo Bayou with the vision of establishing a major trading post and port. They named the city after General Sam Houston, a key figure in the Texas Revolution and the first president of the Republic of Texas, which had gained independence from Mexico earlier that year.",
      sidepara3: "We can serve you the best services in this Hotel",
      sidepara4: "Our service is the best in all the Hotels",
      sidepara5: "Please Contant Our Phone Number",
    },
    {
      id: 6,
      title: "New York",
      image: "/images/dest-6.jpg",
      desc9: "New York City, situated on the northeastern coast of the United States, is renowned as a bustling metropolis with a rich tapestry of history, culture, and commerce. Initially inhabited by Native American tribes, European exploration began in the early 17th century, ultimately leading to Dutch settlement and the establishment of New Amsterdam on the southern tip of Manhattan Island. In 1664, the English captured the area and renamed it New York, a pivotal moment that shaped its colonial and later American identity.",
      sidepara9: "York City stands as the largest city in the United States and a symbol of opportunity and ambition. It continues to attract millions of visitors annually to its world-class museums, Broadway theaters, and iconic landmarks such as Central Park and Times Square. As a global center for finance, media, fashion, and technology, New York City remains at the forefront of innovation and creativity, embodying the spirit of diversity and resilience that defines the American experience.",
      sidepara3: "We can serve you the best services in this Hotel",
      sidepara4: "Our service is the best in all the Hotels",
      sidepara5: "Please Contant Our Phone Number",
    },
  ]
  
  export default Sdata